"""Rule domain models and execution results."""

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import StrEnum

from app.domain.workbooks.models import CellValue


class RuleType(StrEnum):
    """Supported foundation rule types."""

    ROW_CLASSIFICATION = "row_classification"
    CELL_TRANSFORMATION = "cell_transformation"
    VALIDATION = "validation"


class RuleOperatorName(StrEnum):
    """Built-in rule operators."""

    EXISTS = "exists"
    IS_EMPTY = "is_empty"
    EQUALS = "equals"
    NOT_EQUALS = "not_equals"
    CONTAINS = "contains"
    STARTS_WITH = "starts_with"
    ENDS_WITH = "ends_with"
    REGEX = "regex"
    GREATER_THAN = "greater_than"
    LESS_THAN = "less_than"
    IN = "in"
    NOT_IN = "not_in"
    FUZZY_EQUALS = "fuzzy_equals"


class RuleSeverity(StrEnum):
    """Validation or classification severity."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


@dataclass(frozen=True, slots=True)
class RuleCondition:
    """Condition evaluated against one dataset field."""

    field: str
    operator: RuleOperatorName
    expected_value: CellValue = None
    expected_values: tuple[CellValue, ...] = ()
    case_sensitive: bool = False
    threshold: float | None = None


@dataclass(frozen=True, slots=True)
class RuleDefinition:
    """Executable rule definition."""

    rule_id: str
    name: str
    rule_type: RuleType
    condition: RuleCondition
    enabled: bool = True
    priority: int = 100
    confidence: float = 1.0
    classification: str | None = None
    transform_to: CellValue = None
    severity: RuleSeverity = RuleSeverity.INFO
    message: str = ""
    metadata: dict[str, object] = dataclass_field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class RulePackDefinition:
    """Versioned rule pack containing typed rules."""

    pack_id: str
    name: str
    version: str
    enabled: bool
    rules: tuple[RuleDefinition, ...]


@dataclass(frozen=True, slots=True)
class RuleMatch:
    """Evidence that a rule matched one row."""

    rule_id: str
    rule_name: str
    rule_type: RuleType
    row_number: int
    field: str
    original_value: CellValue
    confidence: float
    message: str
    metadata: dict[str, object] = dataclass_field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class RowClassification:
    """Classification assigned to a row by a rule."""

    rule_id: str
    row_number: int
    classification: str
    severity: RuleSeverity
    message: str


@dataclass(frozen=True, slots=True)
class CellTransformation:
    """Suggested cell transformation generated by a rule."""

    rule_id: str
    row_number: int
    field: str
    original_value: CellValue
    transformed_value: CellValue
    message: str


@dataclass(frozen=True, slots=True)
class ValidationFinding:
    """Validation finding generated by a rule."""

    rule_id: str
    row_number: int
    field: str
    severity: RuleSeverity
    message: str


@dataclass(frozen=True, slots=True)
class RuleExecutionReport:
    """Structured report generated by rule execution."""

    template_id: str
    row_count: int
    rules_evaluated: int
    matches: tuple[RuleMatch, ...]
    classifications: tuple[RowClassification, ...]
    transformations: tuple[CellTransformation, ...]
    validation_findings: tuple[ValidationFinding, ...]
    routed_rows: tuple["RoutedRow", ...] = ()


@dataclass(frozen=True, slots=True)
class RoutedRow:
    """Final route assigned to a row after rule evaluation."""

    row_number: int
    route: str
    reason: str
