"""Apply rule-generated transformations to intermediate datasets."""

from app.domain.datasets.models import DatasetCell, DatasetRow, IntermediateDataset
from app.domain.rules.models import RuleExecutionReport
from app.domain.workbooks.models import CellValue


class RuleTransformationApplier:
    """Apply deterministic cell transformations generated by rule evaluation."""

    def apply(
        self,
        *,
        dataset: IntermediateDataset,
        rule_report: RuleExecutionReport,
    ) -> IntermediateDataset:
        """Return a dataset with rule transformations applied."""
        transformations: dict[tuple[int, str], CellValue] = {}
        for transformation in rule_report.transformations:
            key = (transformation.row_number, transformation.field)
            transformations.setdefault(key, transformation.transformed_value)

        if not transformations:
            return dataset

        return IntermediateDataset(
            template_id=dataset.template_id,
            sheet_name=dataset.sheet_name,
            rows=tuple(
                self._apply_row(row=row, transformations=transformations)
                for row in dataset.rows
            ),
            removed_fields=dataset.removed_fields,
        )

    @staticmethod
    def _apply_row(
        *,
        row: DatasetRow,
        transformations: dict[tuple[int, str], CellValue],
    ) -> DatasetRow:
        return DatasetRow(
            source_row_number=row.source_row_number,
            cells=tuple(
                DatasetCell(
                    field=cell.field,
                    source_header=cell.source_header,
                    value=transformations.get((row.source_row_number, cell.field), cell.value),
                )
                for cell in row.cells
            ),
            confidence=row.confidence,
        )
