"""Add UserIdentity and make password nullable

Revision ID: b1de5f578512
Revises: e754f4527f25
Create Date: 2026-08-13 20:14:33.739426

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1de5f578512"
down_revision: str | Sequence[str] | None = "e754f4527f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("provider_subject", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_user_identities_provider_subject"
        ),
    )
    with op.batch_alter_table("user_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_identities_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_identities_provider"), ["provider"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_identities_provider_subject"), ["provider_subject"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_identities_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("user_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_identities_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_identities_provider_subject"))
        batch_op.drop_index(batch_op.f("ix_user_identities_provider"))
        batch_op.drop_index(batch_op.f("ix_user_identities_email"))

    op.drop_table("user_identities")
    # ### end Alembic commands ###
