"""initial_schema

Revision ID: dcfb3ac65607
Revises: 
Create Date: 2026-08-13 00:01:07.102748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfb3ac65607'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_table('processing_reports',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('clean_rows', sa.Integer(), nullable=False),
    sa.Column('removed_rows', sa.Integer(), nullable=False),
    sa.Column('needs_review_rows', sa.Integer(), nullable=False),
    sa.Column('rule_matches', sa.JSON(), nullable=False),
    sa.Column('validation_findings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('processing_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_reports.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_outputs')
    op.drop_table('processing_reports')
    op.drop_table('jobs')
    # ### end Alembic commands ###
