"""Add auth models

Revision ID: e754f4527f25
Revises: dcfb3ac65607
Create Date: 2026-08-13 16:34:49.400111

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e754f4527f25"
down_revision: str | Sequence[str] | None = "dcfb3ac65607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "tenants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_memberships_tenant_id_tenants"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tenant_memberships_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenant_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_tenant_id"),
            ["tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_user_id"),
            ["user_id"],
            unique=False,
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:

        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_user_id_users"), "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_tenant_id_tenants"), "tenants", ["tenant_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_jobs_tenant_id_tenants"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_jobs_user_id_users"), type_="foreignkey")

    op.drop_table("tenant_memberships")
    op.drop_table("tenants")
    op.drop_table("users")
    # ### end Alembic commands ###
