"""Add auth models

Revision ID: e754f4527f25
Revises: dcfb3ac65607
Create Date: 2026-08-13 16:34:49.400111

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e754f4527f25"
down_revision: str | Sequence[str] | None = "dcfb3ac65607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_jobs_stored_filename"), ["stored_filename"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_user_id_users"), "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_tenant_id_tenants"), "tenants", ["tenant_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_jobs_tenant_id_tenants"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_jobs_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("uq_jobs_stored_filename"), type_="unique")

    # ### end Alembic commands ###
