"""Processing context shared across pipeline stages."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from uuid import uuid4

from app.domain.templates.models import TemplateDefinition
from app.engine.metrics import StageMetric


@dataclass(slots=True)
class ProcessingContext:
    """State object passed through every pipeline stage."""

    template: TemplateDefinition
    input_path: Path | None = None
    output_dir: Path | None = None
    job_id: str = field(default_factory=lambda: str(uuid4()))
    data: Any | None = None
    removed_rows: list[dict[str, Any]] = field(default_factory=list)
    needs_review_rows: list[dict[str, Any]] = field(default_factory=list)
    audit_events: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metrics: list[StageMetric] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def template_id(self) -> str:
        """Return the active template identifier."""
        return self.template.id

    def add_warning(self, message: str) -> None:
        """Record a non-fatal processing warning."""
        self.warnings.append(message)

    def add_audit_event(self, event: dict[str, Any]) -> None:
        """Record an audit event generated by a stage."""
        self.audit_events.append(event)

    def add_metric(self, metric: StageMetric) -> None:
        """Record execution metrics for a pipeline stage."""
        self.metrics.append(metric)

